spring.application.name=BloggingProject
spring.datasource.url =jdbc:mysql://localhost:3306/blogpost
spring.datasource.username =root
spring.datasource.password= asfak@<>9302580176
spring.jpa.properties.hibenate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update
razorpay.key=rzp_test_SQPFf79szg5Zcc
razorpay.secret =aD9CxW5rT6TucN4EFkYr6Bbx
payment.amount = 1000
spring.security.user.name = Asfak@gmail.com
spring.security.user.password= Asfak

